### PR TITLE
SDDI base Docker build CKAN 2.10.3

### PR DESCRIPTION
**Pull request by ilchebedelovski**
This PR contains modifications of the following parts in the base image:
- The source image is ckan-base 2.10
- The spatial extension is installed from the official repository
- The runtime is Alpine based

### CODE REVIEW

**Comment by BWibo** [comment]
CKAN `2.10.4` has been released. https://github.com/ckan/ckan/releases/tag/ckan-2.10.4

**Comment by BWibo** [comment]
What's the status of this PR?

By now, there is an official Debian version of the CKAN images: https://github.com/ckan/ckan-docker-base?
This might fix the issues we have with `ckanext-spatial` and give us an official base image we can rely on.
We should try them out!

In addition, CKAN 2.11 is on it's way.

**Comment by MarijaKnezevic** [comment]
The developer is currently working on creating the "master plugin", which will solve many problems in future. I have received the first draft from the developer and am now testing the functions to see if anything is still missing.
Once we have finished the master plugin, it would be necessary to complete this PR.

**Comment by aleksandralazoroska** [comment]
The source image has been updated to ckan-base 2.11

**Comment by MarijaKnezevic** [comment]
To update to CKAN 2.11, please follow the development idea and logic that was previously discussed with @ilchebedelovski and @BWibo and started [here](https://github.com/tum-gis/ckan-docker/blob/2.1.2/sddi-base/Dockerfile).

**Comment by BWibo** [comment]
@MarijaKnezevic @aleksandralazoroska 
For moving to 2.11 it is most important, that we move away from the keitaronic base images and move to the official ckan base images. That should be possible now, as they are available based on Debian now.

**Comment by BWibo** [comment]
@MarijaKnezevic 
This PR is outdated and can be closed, right?

**Comment by MarijaKnezevic** [comment]
@BWibo yes, this can be closed.
Will not have a release for 2.10 and we will continue to work on updating SDDI to CKAN 2.11 which is current CKAN version

**Pull request closed without merging**
