### PR TITLE
SDDI base Docker build CKAN 2.11.0

### PR DESCRIPTION
**Pull request by aleksandralazoroska**
- Updated the `Dockerfile` for CKAN 2.11.0
- Added SDDI Plugins for CKAN 2.11.
- Updated versions for `uWSGI`, `gevent`, and `greenlet`

### CODE REVIEW

**Comment by BWibo** [comment]
@aleksandralazoroska
Thx for the work on the PR. I just  found the time to take a quick look that lead to a question. 

Is there a specific reason why are you building CKAN inside the image and not use the [official base image](https://github.com/ckan/ckan-docker-base) instead?
This is a complicated task that we would have to maintain in the future.

**Comment by MarijaKnezevic** [comment]
Please remove `ckanext-grouphierarchy` [L115-L126](https://github.com/tum-gis/ckan-docker/blob/ec111e3fb0f9495a57bbc83ebbd3762aa24d432a/sddi-base/Dockerfile#L115-L126) and `ckanext-composite` , `ckanext-repeating` , `ckanext-password-policy` [L159-L190](https://github.com/tum-gis/ckan-docker/blob/ec111e3fb0f9495a57bbc83ebbd3762aa24d432a/sddi-base/Dockerfile#L159-L190).

Some of those plugins are either not supported in CKAN 2.11 or have been migrated to `ckanext-scheme-sddi` or `ckanext-theme-sddi`.
Please use plugins mentioned in #64

**Comment by MarijaKnezevic** [comment]
@aleksandralazoroska did you tried to use official base image?
As Bruno mentioned in #55 , since Debian-based images are now available, it should be possible to use official ckan base images. 

We had problems with `ckanext-spatial` and Bruno realized that the installation requires a Debian-based image, and for that we used an image from Keitaro because at the time there was no Debian-based image of CKAN. But from CKAN 2.11. it should be possible as they are offering official CKAN Debian Based images.

The idea is to keep the maintenance effort for this development as low as possible and to use community contributions as much as possible.

**Comment by aleksandralazoroska** [comment]
Closing the PR because of auth issues on Container Registry.

**Pull request closed without merging**
