### PR TITLE
sddi-urban Image for LHM Metadatenkatalog

### PR DESCRIPTION
**Pull request by gislab-augsburg**
We need an extra Docker Image `sddi-urban` with a slightly different set of CKAN extensions and configuration for the Metadatenkatalog of Landeshauptstadt München (LHM). We tried to adapt to the structure and systematics of the other SDDI image flavors. Therefor, the following changes are proposed:

- extra directory with dockerfiles for `sddi-urban`
- changed readme file including the `sddi-urban` image characteristics
- changed workflow files according to the other flavors
- changed build files according to the other flavors

As discussed with @MarijaKnezevic we make this pull request for the `devel` branch, but the changes were developed based the `main` branch, so the commits a9c8bcb to 15685c6 of `main` are also part of this PR. 

In general, the proposed changes are up for discussion to fit into your repo and fullfill the LHM requirements. We will also continue development on the Metadatenkatalog throughout 2024, so further changes will come. But we decided not to wait too long in order to prevent diverging of the branches and concepts too much.

### CODE REVIEW

**Comment by BWibo** [comment]
Do you want to distribute the image through the Docker registry of this repo too? If yes, we would need to extend the CI/CD pipelines for that. A different/additional target repo is possible too.

**Comment by gislab-augsburg** [comment]
@BWibo 

Yes, our plan was to distribute the image through the Docker registry of this repo. This week it turned out that OpenDataPortal Munich, another LHM product which will use sddi-ckan-k8s, will need an additional image (sddi-odp or so). So maybe a different/additional target repo would make sense, I am not sure.

@MandanaMoshref What do you think?

Also I have to say that this PR does not represent the current state of our sddi-urban image any more, we have further developed it in another branch an development will go on throughout 2024.

I would suggest we discuss these things in our meeting next week.

**Comment by BWibo** [comment]
Hey there, what's the status of this PR? Is it still needed or can we close this?

**Comment by BWibo** [comment]
OK, thx. So this is generally ready for review and the additions you mentioned above?

**Comment by gislab-augsburg** [comment]
Yes, it's ready for review and the additions 👍 👍

**Comment by BWibo** [comment]
Hey all, I finally managed to take a look at this and think about how to get this merged and maintained in the future.
I've come to the conclusion, that the concept of managing all images in this repo in separate folders is not the best.

I suggest we have a meeting soon to discuss how to proceed. I would like to explain what problems I see and what benefits a solution with separate repos would have.

**Comment by gislab-augsburg** [comment]
@BWibo Ok, I'll set up a meeting  to discuss how to proceed via Email.

**Comment by BWibo** [comment]
Closing, as discussed in the meeting.

**Pull request closed without merging**
