### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by BWibo**
Please also check the following points carefully:

- [x] Is the `CHANGELOG.md` complete?
- [x] Are all versions pinned properly for the release?
- [x] Are there any changes, new configuration, ... that needs to be propagated to https://github.com/tum-gis/sddi-ckan-k8s?
- [x] Are all new features/extensions/... documented in `README.md`?
- [x] Are there any breaking changes, that are not documented in `CHANGELOG.md` jet?
  - [x] Changes, that require additional manual action by admins, when updating to this version, e.g. database updates, updats to existing user accounts, ...?
  - [x] Explicitly test, if updating an exisitng instance to this version works. E.g. use an existing catalog or a fresh catalog with `v1.3.0` and update it to this version. There should be users/entries/resources usw. in the catalog before the update.

### CODE REVIEW

**Comment by BWibo** [comment]
@MarijaKnezevic Please test the latest im from this PR. See #51 too. This will be helpful.

**Review by MarijaKnezevic — APPROVED** [review]

**Comment by BWibo** [comment]
@MarijaKnezevic: Check the latest release of `ckanext-spatial`: https://github.com/ckan/ckanext-spatial/releases/tag/v2.1.0
This should allow to use the original version and not the fork, right?

**Comment by MarijaKnezevic** [comment]
@BWibo Not really. In our forked spatial there are two files [spatial_form.js](https://github.com/MarijaKnezevic/ckanext-spatial/blob/59d6c3e913ac3279074f8a27f43db2c002e8b9b5/ckanext/spatial/public/js/spatial_form.js) and [webassets.yml](https://github.com/MarijaKnezevic/ckanext-spatial/blob/45c195021845a118e901dc88e4da00262cac6de3/ckanext/spatial/public/webassets.yml) which were added/adapted to make the plugin work with our scheming.
In [ckanext-spatial v2.1.0](https://github.com/ckan/ckanext-spatial/releases/tag/v2.1.0) not all the features we need are included. From the changelog file of v.2.1.0 I can see that the problem with the background map has been fixed, which is currently our problem. I posted [PR 317](https://github.com/ckan/ckanext-spatial/issues/317) and added the other background map in our [Docker file](https://github.com/tum-gis/ckan-docker/blob/release/2.0.0/sddi-base/Dockerfile#L219-L221) as suggested in this PR.
I am aware that more improvements are coming with the new version of Spatial and that we currently have an additional plugin to maintain. But I have discussed with Thomas and Andreas that we urgently need to find a solution to create a plugin that will extend our need and that we basically need to create one "master SDDI plugin" where plugin functionality is going to be extended because now we have just one more thing to maintain.

**Comment by BWibo** [comment]
@MarijaKnezevic OK, your decision. Is this tested and ready to release then?

**Comment by MarijaKnezevic** [comment]
@BWibo yes, it is tested and it passed the pentest. It can be released.

**Comment by MarijaKnezevic** [comment]
@BWibo could you please update our "savenow" instance?

**Comment by MarijaKnezevic** [comment]
@BWibo I've created a backup for our Savenow instance. Could you please update it?

**Pull request merged**
